- Makefile
- src/Makefile
- src/enclave-agent/Cargo.toml
- src/enclave-agent/Makefile
- src/enclave-agent/src/main.rs
- src/libs/Cargo.toml
- src/libs/protocols/Cargo.toml
- src/libs/protocols/build.rs
- src/libs/protocols/protos/image.proto
- src/libs/protocols/src/lib.rs
1 As the ttrpc server, it receive requests sent by shim-rune.
2 Pull and unpack image.
3 Convert the image to the encrypted filesystem as the mount source of the app container.
Signed-off-by: Zhiwei Han <zhiwei1.han@intel.com>
> enclave-agent: it is responsible for image management service.

- CODEOWNERS
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> add codeowner from maintainers

- src/shim/README.md
> docs: fix shim configuration

- src/shim/go.mod
- src/shim/runtime/v2/rune/v2/agent.go
- src/shim/runtime/v2/rune/v2/image.go
- src/shim/runtime/v2/rune/v2/service.go
- src/shim/vendor/modules.txt
> shim: use standard errors

- src/shim/config/config.toml
- tools/packaging/build/Dockerfile
- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/agent-enclave-bundle/config.json
- tools/packaging/build/agent-enclave-bundle/enclave-agent.yaml
- tools/packaging/build/agent-enclave-bundle/gen_bundle.sh
- tools/packaging/build/agent-enclave-bundle/jq.filter
- tools/packaging/build/boot-instance-bundle/Dockerfile
- tools/packaging/build/boot-instance-bundle/gen_bundle.sh
- tools/packaging/build/boot-instance-bundle/init.yaml
- tools/packaging/build/boot-instance-bundle/jq.filter
- tools/packaging/build/boot-instance-bundle/v1-0001-init-code-change.patch
- tools/packaging/build/build_payload.sh
- tools/packaging/deploy/ccruntime.yaml
- tools/packaging/deploy/enclave-cc-deploy.sh
> packaging: scripts to prepare artifacts and payload image

- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/boot-instance-bundle/Dockerfile
- tools/packaging/deploy/enclave-cc-deploy.sh
> packaging: make post-uninstall more robust

- README.md
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> README: add enclave-cc introduction and motivation

- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/agent-enclave-bundle/config.json.template
- tools/packaging/build/agent-enclave-bundle/gen_bundle.sh
- tools/packaging/build/agent-enclave-bundle/jq.filter
- tools/packaging/build/agent-enclave-bundle/sgx-mode-config.filter
- tools/packaging/build/boot-instance-bundle/Dockerfile
- tools/packaging/build/boot-instance-bundle/gen_bundle.sh
- tools/packaging/build/boot-instance-bundle/jq.filter
- tools/packaging/build/build_payload.sh
> build: allow run enclave-cc in SGX simulation mode

- .github/workflows/payload.yaml
- .github/workflows/release.yaml
- tools/packaging/build/build_payload.sh
This PR adds the needed fixes for automating the payload generation, be it on every push or when tagging a release.
Please, see each commit message for more details on what's been done on each commit.
https://github.com/fidencio/enclave-cc/actions/runs/3387943466/jobs/5629325048 is the current run where I'm trying to exercise this patches.
> Automate payload generation -- 2nd try

- tools/packaging/build/build_payload.sh
> tools: use install to copy the installer script

- .github/workflows/e2e.yaml
- test/e2e/hello-world-unencrypted.json
- test/e2e/sandbox.json
> ci: add simple e2e tests

- .gitignore
- src/enclave-agent/src/main.rs
- src/enclave-agent/src/services/images.rs
- src/enclave-agent/src/services/mod.rs
Separate services from the program entry
Signed-off-by: Xing, Haokun <haokun.xin@intel.com>
> refactor: modulize enclave agent

- src/enclave-agent/src/services/images.rs
The container id is passed from the shim, the agent is able to verify it and unable to modify it.
Signed-off-by: Xing, Haokun <haokun.xin@intel.com>
> fix: verify container id

- tools/packaging/build/build_payload.sh
> tools: build shim in a container

- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/agent-enclave-bundle/enclave-agent.yaml
> build EAA/RATS-TLS

- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/agent-enclave-bundle/enclave-agent.yaml
> build: make RATS-TLS available for enclave-agent build

- src/enclave-agent/Cargo.toml
Signed-off-by: Haokun Xing <haokun.xin@intel.com>
> feature: enable cosign signature

- tools/packaging/build/agent-enclave-bundle/sgx-mode-config.filter
Signed-off-by: Liucheng Hu <liucheng.hu@intel.com>
Fix sgx path and config PCCS
Fixes: #84
> fix sgx path and config PCCS

- src/enclave-agent/Cargo.lock
- src/enclave-agent/Cargo.toml
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
> enclave-agent: remove unused dependency

- src/enclave-agent/Cargo.lock
- src/enclave-agent/Cargo.toml
In preparation for CoCo 0.5 release, bumped the image-rs for the commit xxx.
> enclave-agent: update image-rs dependency

- tools/packaging/build/Dockerfile
As
https://github.com/kubernetes/release/issues/2862#issuecomment-1565660554, public key release of kubernetes have been changed.
> packaging: fix payload build

- src/enclave-agent/Cargo.lock
- src/enclave-agent/Cargo.toml
- Bump image-rs to the v0.6.0 release
> deps: Bump image-rs

- tools/packaging/build/agent-enclave-bundle/jq.filter
> improve pull stability of multi-layer images

- .github/workflows/links.yml
- README.md
- docs/design.md
- docs/shim-rune.md
Contributing to https://github.com/confidential-containers/confidential-containers/issues/83
> ci: add link checker and fix links

- .github/workflows/basic.yaml
- src/enclave-agent/Cargo.lock
- src/enclave-agent/Cargo.toml
- src/runtime-boot/init/Cargo.lock
- src/runtime-boot/init/Cargo.toml
- src/runtime-boot/init/src/main.rs
- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/boot-instance-bundle/Dockerfile
> Update to Occlum 0.29.7

- .github/dependabot.yml
> dependabot: check enclave-agent dependencies

- tools/packaging/build/Dockerfile
> build: move to pkgs.k8s.io APT repo

- tools/packaging/build/agent-enclave-bundle/Dockerfile
- tools/packaging/build/boot-instance-bundle/Dockerfile
> Occlum v0.30.0

- src/runtime-boot/init/src/main.rs
- tools/packaging/build/unified-bundle/Dockerfile
- tools/packaging/build/unified-bundle/enclave-agent-cc-kbc.yaml
- tools/packaging/build/unified-bundle/enclave-agent-sample-kbc.yaml
> Move to Ubuntu 22.04 based bundle

- .github/workflows/basic.yaml
- .github/workflows/e2e.yaml
- .github/workflows/links.yml
- .github/workflows/payload.yaml
- .github/workflows/release.yaml
- src/runtime-boot/init/Cargo.lock
- src/runtime-boot/init/Cargo.toml
- src/runtime-boot/init/src/main.rs
- src/shim/go.mod
- tools/packaging/build/build_payload.sh
> workflow updates
