.github/workflows/release.yaml
The release tag will be, according to the other repos under the Confidential Containers organisation, for instance, v0.2.0.
Prior to this patch we're considering it'd be 0.2.0, without the initial `v`.
=> github: Fix release tag format

src/enclave-agent/Cargo.toml
As image-rs has tagged its `v0.2.0` release, let's make sure we're using it in what will become the `v0.2.0` release of Enclave CC.
=> enclave-agent: Bump image-rs to `v0.2.0`

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, src/enclave-agent/Makefile, tools/packaging/build/agent-enclave-bundle/Dockerfile, tools/packaging/build/agent-enclave-bundle/enclave-agent.yaml
The new rev of the image-rs introduces the rats-tls, to refer it, we install rats-tls in the complie env and update the reference to the image-rs.
Signed-off-by: Xin, Haokun <haokun.xin@intel.com>
Closes: #60
=> fix: refer new image-rs

.github/workflows/basic.yaml
newer golang.org/x/sys depend on Go 1.17+ versions. Since 1.16 is no longer supported, we can just drop it in our CI to get golang.org/x/sys and other dependencies updated.
=> ci: do not test with Go 1.16 anymore

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
image-rs has released its v0.3.0 release earlier Today, following the v0.3.0 Confidential Containers release process.
The v0.3.0 is based on exactly the same commit we've been using already, so no changes are expected for us.
=> enclave-agent: Update image-rs to v0.3.0

tools/packaging/build/agent-enclave-bundle/Dockerfile
We've noticed that in the fcbf7c924d280fe328aa96de09ab9ce72bf5ccb9 commit the image has grown from ~700MB to 1.6GB.  The commit introduced some changes that, for sure, should make the image bigger, but not *that big*.
After analysing the image content, I've noticed that the whole $HOME/.rustup has been added to the image, and that's most likely the root cause of the issue.
=> build: Remove $HOME/.rustup content from the final image

tools/packaging/build/agent-enclave-bundle/Dockerfile
This was also added by fcbf7c924d280fe328aa96de09ab9ce72bf5ccb9 and causes a /enclave-cc directory, with the enclave-cc source code, vendors, whatnot to be left as part of the agent-instance.tar.
=> build: Remove /enclave-cc from the final image

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, src/enclave-agent/src/config.rs, src/enclave-agent/src/main.rs, src/enclave-agent/src/services/images.rs
This pr does some little refactoring, including:
- use rstest for test cases
- reorder the dependency definitions, and delete useless features
- use log and env_logger crate to log instead of println.
=> Refactor enclave-agent

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
That's the image-rs version that will become the v0.4.0, and the main change that affects Enclave CC is the way we build it, as we can simply use the `enclave-cc` feature.
=> enclave-agent: Bump image-rs to 948db858579be538724266a650e840e75e7e824d

src/runtime-boot/init/src/main.rs, tools/packaging/build/boot-instance-bundle/jq.filter
Setting rootfs_entry to /bin allowed to run binaries from that directory only. / works too and allows binaries from any path to run.
At the same time, Occlum did not get all the dynamically linked libraries loaded due to missing lib search paths. Add trusted LD_LIBRARY_PATH setting for the most common paths.
=> boot-instance: allow more images to run

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
Commit c448ebc9 moved to a new image-rs that had re-organized its features. The new "enclave-cc" feature does not enable signature-cosign by default but our default test images depend on it so enable it.
/cc @Xynnn007
=> enclave-agent: enable signature-cosign image-rs feature

tools/packaging/build/Dockerfile
Instead of using CentOS as the base image, let's follow what's been done for the preInstall / postInstall / Kata Containers payload, and switch to using an Ubuntu image instead.
=> payload: Use ubuntu 20.04 image as base

.github/dependabot.yml
It requires more work to get this working so keep using v1.1.x.
=> dependabot: ignore containerd/ttrpc v1.2.x

.github/workflows/basic.yaml, .github/workflows/e2e.yaml
Github Actions report the following:
shim basic test (ubuntu-22.04, 1.20.x)
Restore cache failed: Dependencies file is not found in
/home/runner/work/enclave-cc/enclave-cc. Supported file pattern: go.sum
Point setup-go to src/shim/go.sum to use cache.
=> ci: use setup-go cache properly

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, test/e2e/decrypt_config-HW.conf, test/e2e/hello-world-encrypted-HW.json, test/e2e/hello-world-encrypted-SIM.json
=> Bring new test images for CI

.github/workflows/release.yaml
Should the release workflow match the push workflow? Currently we are releasing a `SIM-cc-kbc` bundle, which does not match our CI bundles. Is this necessary? 
@Xynnn007 @mythi @dcmiddle
=> Workflows: fix release workflow

tools/packaging/build/agent-enclave-bundle/Dockerfile
At the same time, it was noticed occlum-sgx-tools is better to pull _sim.so libraries from instead of separately installing the SDK package.
=> build: lock Occlum version

.github/workflows/payload.yaml
dependabot pushes to the repository trigger payload.yaml workflows which should not happen at all.
It's likely that Github does not like the branch names without hyphens and the filter gets broken.
=> workflows: fix payload push trigger syntax

docs/ci-setup.md
In enclave-cc CI we have an image policy to control the allowance of the images, and a 32-byte key to decrypt the encrypted image from CoCo Community.
=> docs: update CI docs for KBS settings

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
Image-rs has been tagged for v0.7.0 release,
so let's use the tagged version.
=> deps: bump dependencies for v0.7.0 release tags

tools/packaging/build/Dockerfile, tools/packaging/build/build_payload.sh, tools/packaging/build/runtimeclass/enclave-cc.yaml, tools/packaging/deploy/enclave-cc-deploy.sh
Kata Containers moved to managing the runtime class creation / deletion, leading to making the Operator "dumber", removing all the runtime class management from there.
Let's adapt to it on the Enclave CC side as well.
=> ccruntime: Manage runtime class creation / deletion

tools/packaging/deploy/enclave-cc-deploy.sh
Instead of using `/runtimeclass/enclave-cc.yaml`, let's use the full path for it `/opt/enclave-cc-artifacts/runtimeclass/enclave-cc.yaml`
This will fix the following error faced on the Operator CI side:
```
ubuntu@operator:~/operator$ kubectl -n confidential-containers-system logs cc-operator-daemon-install-j4fxn -c cc-runtime-install-pod
copying enclave-cc artifacts onto host
Add enclave-cc as a supported runtime for containerd
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.enclave-cc, overwriting
Creating the runtime classes
error: the path "/runtimeclass/enclave-cc.yaml" does not exist
```
=> enclave-cc-deploy: Fix runtimeclass path

.github/workflows/basic.yaml, src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, tools/packaging/build/agent-enclave-bundle/Dockerfile
the latest version makes devicemapper dependency as optional so we get to drop it from the builds.
=> enclave-agent: update image-rs dependency

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, src/enclave-agent/src/config.rs, src/enclave-agent/src/main.rs
clap v2.33.3 is three years old and automated dependabot updates won't work anymore.
Rework enclave-agent command line args handling to the latest Derive API from clap and move to v4.4.6.
=> enclave-agent: move to clap v3 Derive API

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
Before cutting image-rs for v0.8.0, make sure the latest image-rs works for enclave-cc
=> Update image-rs to v0.8.0 candidate

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
The candidate image-rs is updated by the PR https://github.com/confidential-containers/guest-components/pull/381.
=> bump: update image-rs to v0.8.0 candidate

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
This is to satisfy step 11 from the release checklist [here](https://github.com/confidential-containers/confidential-containers/issues/145).
=> bump: Use v0.8.0 tag for image-rs

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml, src/runtime-boot/init/Cargo.toml, src/runtime-boot/init/src/main.rs
This PR is related to image-rs PR https://github.com/confidential-containers/guest-components/pull/385 and replaces 
https://github.com/confidential-containers/enclave-cc/pull/266 for easier reading
After merge of image-rs PR, branch in Cargo.toml will be reverted
Makes Runtime boot use key stored in file by image-rs/enclave agent.
After merging and fixes next step will be to seal/unseal the file with SGX
Fixes: #149
=> Runtime boot using a randomly generated key from image-rs passed inside enclave sefs

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
in old image-rs we use Attestation Agent as a lib inside to request for keys. After some refactoring, AA remains only the attestation parts. This patch updates image-rs version after that refactoring.
see https://github.com/confidential-containers/guest-components/issues/412
=> bump: image-rs to new version

docs/shim-rune.md, src/runtime-boot/init/Cargo.lock, src/runtime-boot/init/Cargo.toml, src/runtime-boot/init/src/main.rs
several places require manual updates that dependabot cannot handle. Help them a bit.
=> help dependabot

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
Doing a manual `Cargo.toml` update to update guest-components and to cleanup leftovers.
=> deps: manual cargo update and cleanup in /src/enclave-agent

tools/packaging/build/unified-bundle/Dockerfile
The latest Occlum release adds EDMM and AMX support. Move to use the latest version without making changes to the features.
The new features will be enabled separately.
=> bundle: update Occlum v0.30.1

.github/workflows/e2e.yaml
If this PR works, I think we can delete the repo runner of `sgx-ecc`. cc @mythi
=> ci: update e2e to use organization runner

src/enclave-agent/Cargo.lock, src/enclave-agent/Cargo.toml
time v0.3.4 has issues with Rust 1.80.0. Manually update
it to the latest with:
`cargo update -p time --precise 0.3.36`
to get builds working with "rust stable".
(+ some minor manual updates too)
=> Rust 1.80.0 fix

.github/dependabot.yml
With the newly added "directories", dependabot can update multiple directories for the same package-ecosystem at once.
=> dependabot: update rust dependencies at once
